[book]
title = "Iterative Development"
authors = ["John M Telford"]
description = "Iterative Websites Development"

language = "en"
multilingual = false

src = "src"
default-theme = "light"

[preprocessor.links]

[output.html.search]
boost-paragraph = 20
